### ISSUE TITLE
Extend Github Actions

### ISSUE THREAD

**Issue by sagudev** [DRFos/es_runtime#1]
Now, as the base work is done, you can additional functionality to GitHub actions, here is list of my favorite:

- Automatic format
- Docs generation and publishing it to GitHub pages
- Annotations (clippy lints)
- Add cache to speed up rebuilding process

I have implemented them [here](https://github.com/sagudev/nanojs/blob/d5c2923891aba2b9b54947c36851cd8bb178aaa4/.github/workflows/rust.yml), so just say which functionality do you want and I will make PR.

**Comment by andrieshiemstra** [comment]
All would be great, i also copied the base work from that lib already :) so thank you!

**Comment by sagudev** [comment]
I must thank you for colors in output. Closing on #2

**Comment by sagudev** [comment]
Just wanted to say one more thing. Caching is doing great. Gitlab's time was around 30 min while here we have 10 min on cached build. With even more steps (formatting, doc publishing, linting)!
