### ISSUE TITLE
Treat clippy warnings as errors.

### ISSUE THREAD

**Issue by sagudev** [DRFos/es_runtime#11]
- [x] Fix clippy warnings
- [x] Run clippy with `-- -D warnings` or maybe [`RUSTFLAGS: -D warnings`](https://github.com/rust-analyzer/rust-analyzer/blob/f03404f6813e9651244aab87d22a137e5219ea0b/.github/workflows/ci.yaml#L19)

**Comment by andrieshiemstra** [comment]
i fixed the warnings, i'll leave it up to you to close this issue if you added all you want to the workflow files

Thanks for the insight in how to use Clippy! 👍

**Comment by sagudev** [comment]
I added all in 5df38a1a4d7b84dd469e5c38e7487bc7ff40a46d

**Comment by sagudev** [comment]
Maybe adding #![deny(warnings)] and #![deny(clippy)] would be better idea, because it would produce errors even outside CI (your pc). So less failed builds.

**Comment by andrieshiemstra** [comment]
i don;t know exacly what you mean by that.. 

i run clippy a lot also on my pc (using 'cargo clippy') and while that does not give errors i sometimes get errors in CI

**Comment by sagudev** [comment]
On your PC you need to run clippy with -- -D warnings or maybe RUSTFLAGS: -D warnings to threat warnings as errors. Maybe prepush hook could make more successful builds.

**Comment by andrieshiemstra** [comment]
added a ref to husky, this will generate git-hooks when you run cargo test
