### ISSUE TITLE
Decission: Do we add stuff like XMLHttpRequest, Fetch Api, Websocket api

### ISSUE THREAD

**Issue by andrieshiemstra** [DRFos/es_runtime#17]
or is that for ESsesLib only?

**Comment by sagudev** [comment]
I thing it should be as pure as possible. Just wrapper over mozjs (actually wrapper over wrapper over wrapper), no implementations.

**Comment by andrieshiemstra** [comment]
Thx, i think i agree

I'll try to make ESsesLib and the commandline tool repo's public sometime doon
