### ISSUE TITLE
Remove as much dependencies as possible

### ISSUE THREAD

**Issue by sagudev** [DRFos/es_runtime#31]
This repo uses 11 dependencies. Mozjs is logical, but others ...
From some dependencies only one function is used.

**Comment by andrieshiemstra** [comment]
is having lots of dependencies a bad thing? i'd think reusing commmon code would be prefereble over reimplementing stuff..

What si the motivation for removing them, ok 1 or two might be implementable differently to save compile time... but thanks to having mozjs in the deps ir won't save a lot :)
