### ISSUE TITLE
Storing EsValueFacade from function call

### ISSUE THREAD

**Issue by Nerixyz** [DRFos/es_runtime#43]
Hi, first of all thanks for this nice simplification of the Spider Monkey interface.

Now I'm rather new to Rust and this library and I wanted to add a global function to "register" functions. These functions are saved in a map and called later. My code looks like this: 
```rust
let rt = EsRuntimeBuilder::new().build();

let mut map = HashMap::new();

rt.add_global_sync_function("test", |args| {
  map.insert(args[0].get_string(), &args[1]);
  Ok(EsValueFacade::undefined())
});
```
This won't compile (Error message: `(dyn es_runtime::esvaluefacade::EsValueConvertible + std::marker::Send + 'static)` cannot be shared between threads safely).

I don't expect it to work like this but this was my only approach. I'd guess doing it like this will conflict with the GC as it doesn't know whether the arguments are still used. 

Now my question is: Is there a proper way of saving a `EsValueFacade` in a map and being able to use it later which won't conflict with the GC and the Rust compiler?

**Comment by andrieshiemstra** [comment]
Hi,

Thanks for trying this lib!

the sync issue is because you're adding a ref (&args[1]) to you map, you should try moving the EsValueFacade from the args vec

e.g.
```rust
rt.add_global_sync_function("test", |mut args| {
  map.insert(args[0].get_string(), args.remove(1));
  Ok(EsValueFacade::undefined())
});
```

which will lead you to the problem that you're moving your map into your closure, which will fail because it is a Fn and not a FnOnce and then it ends up not being what you want because you can't access the map annymore :)

long story short, you'll end up with something like this

```rust

lazy_static! {
   // keep the map in your app somewhere
    static ref MAP_MTX_ARC: Arc<Mutex<HashMap<String, EsValueFacade>>> =
        Arc::new(Mutex::new(HashMap::new()));
}

#[cfg(test)]
pub mod tests {
#[test]
fn test_nerixyz() {
    let rt =EsRuntimeBuilder::new().build();

    rt.add_global_sync_function("test", |mut args| {

        // lock the mutex and get a &mut HashMap
        let mtx = &*MAP_MTX_ARC.clone();
        let locked_map = &mut *mtx.lock().unwrap();

        // use get_string.to_string as key because a &str might not live long enough
        // also remove EsValueFacade from args so we have  EsValueFacade and not a &EsValueFacade
        locked_map.insert(args[0].get_string().to_string(), args.remove(1));
        
        // return null
        Ok(EsValueFacade::undefined())
    });
}
```

**Comment by andrieshiemstra** [comment]
hope this helps, good luck!

p.s. i'm currently more active on the quickjs version (https://github.com/HiRoFa/quickjs_es_runtime) as the mozjs package seems less actively developed since mozila fired a lot of devs working on servo..

Kind regards
Andries
